### ISSUE TITLE
Rework color table approach

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/leaflet-gl-vector-layer#1]
- It should be possible to fully configure the set of color tables that are shown in the panel. See also https://github.com/stcorp/atmosphere-virtual-lab/issues/1.
- The built-in color maps should be a minimal set (TBD which maps). Also, for each map, we should not provide the full LUT but just a generator function based on gradient edge points (we don't want to embed KBs of data points).
- Remove any reference to S5pPal
- Combine color table editor and table selection in a single panel (behind the pallet icon). We should not pollute the interface with more than one icon for color tables.
- The 'reset' button should also be within this single panel, and should be better defined. Resetting the table itself should be possible by making sure that the manually provided color table is always a table that can be selected in the list of colormaps. Resetting the color min/max range is something that would require a button, but it shouldn't revert to the manually provided range, but to the actual data min/max range.

**Comment by mkaipiainen** [comment]
Regarding the last point, in combination with https://github.com/stcorp/atmosphere-virtual-lab/issues/1, do I understand correctly that we'd have to be able to pass multiple colormaps to the leaflet-gl-vector-layer-plugin, and always only show the colormaps that  have been passed in (and nothing else)? I assume this would be done via a 'colormaps' parameter or some such. 

Should there still be retained the option to pass a 'default' colormap via the colormap-parameter? And if not, what should the reset button reset the colormap to? Perhaps the first of the passed colormaps?

**Comment by svniemeijer** [comment]
That is indeed the idea. As a user of this component (=developer) it should be possible to fully define the set of color tables that are used/shown.
It is fine to have some default set to work with if none are defined, but for AVL we want to be able to align the color tables in this component with those used in the 3D map plots. And we don't want this relationship to be hardcoded.

**Comment by mkaipiainen** [comment]
Alright, this is almost functional already. I suppose the remaining question is what the reset button should do in case of multiple colormaps having been passed. Should it reset to the first given colormap? Or should there be a separate parameter for a default colormap (basically how it works currently with the 'colormap' parameter)?

**Comment by svniemeijer** [comment]
For me the 'reset' would be a 'reset' to what is was when the plot was initially shown. And this would work per-layer. It means resetting the color table to whatever was used when the layer was initially added if an explicit color table was provided, then that color table should be used and if none was provided then the default color table should be used.

This is especially important if a custom color table is passed and a user starts modifying the colors/ranges in the color table editor. A reset should set it back to whatever it was at the beginning.

If a custom color table is passed, then it would also be useful to have this color table show up in the color table list (don't know if that is already the case). However, any user modifications using the color table editor should not change anything in the color table list (i.e. it only modifies the color table for that specific layer).

Furthermore, I would use the first color table from the color table list as default color table if none is provided.

**Comment by svniemeijer** [comment]
Closing this issue. Any further improvements will be captured as new issues.
