### ISSUE TITLE
Get rid of 'Layer 1' box in bottom left

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/leaflet-gl-vector-layer#3]

**Comment by mkaipiainen** [comment]
Right now the box is relevant when having multiple layers, you'll have one box per layer, and you can switch between them (and thus set the colors etc. individually on a layer-per-layer basis). Should the box still be removed, and if so, should I create an alternative way to switch between layers/toggle them off/on? Or should all layers be configured simultaneously (this becomes a problem especially if the data min/max ranges of the different layers are vastly different)?

**Comment by mkaipiainen** [comment]
![image](https://user-images.githubusercontent.com/105204322/190092046-55de107d-ebdb-48a4-8f67-b1a2ce30838d.png)

Example of having two layers.

**Comment by svniemeijer** [comment]
If it is a custom selection box to determine for which layer to modify the color table, then please add this selection into the single dialog panel as discussed in #1
